// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATjdwH0Hmu1wVKH1JZSdOvxSYgdBrkpTU',
    appId: '1:685156900683:web:8288bc6820a332a36a12ce',
    messagingSenderId: '685156900683',
    projectId: 'emailauth-c4de1',
    authDomain: 'emailauth-c4de1.firebaseapp.com',
    storageBucket: 'emailauth-c4de1.appspot.com',
    measurementId: 'G-NRSPVVFK14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLxSV97QbJgaFvdRQngnL2OXW2rAoMdBw',
    appId: '1:685156900683:android:9ee3befe65f6460b6a12ce',
    messagingSenderId: '685156900683',
    projectId: 'emailauth-c4de1',
    storageBucket: 'emailauth-c4de1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArUk7u8xBaaZae9TvyS6SZS2Uul-Yhjtg',
    appId: '1:685156900683:ios:a24ff9761663dda76a12ce',
    messagingSenderId: '685156900683',
    projectId: 'emailauth-c4de1',
    storageBucket: 'emailauth-c4de1.appspot.com',
    iosClientId: '685156900683-94doqhfsvfc49r1repe86jsovj3t41uc.apps.googleusercontent.com',
    iosBundleId: 'com.example.edubot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArUk7u8xBaaZae9TvyS6SZS2Uul-Yhjtg',
    appId: '1:685156900683:ios:a24ff9761663dda76a12ce',
    messagingSenderId: '685156900683',
    projectId: 'emailauth-c4de1',
    storageBucket: 'emailauth-c4de1.appspot.com',
    iosClientId: '685156900683-94doqhfsvfc49r1repe86jsovj3t41uc.apps.googleusercontent.com',
    iosBundleId: 'com.example.edubot',
  );
}
